name: WordCloud

# everday at 00:00 UTC.
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with WordCloud
    runs-on: ubuntu-latest
    steps:
      - uses: MrNobody65/profile-wordcloud@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          IGNORE_FILE_TYPES: ""
          IGNORE_REPOS: ""
